### ISSUE TITLE
Add GOARCH, GOOS query parameters

### ISSUE THREAD

**Issue by dolmen** [golang/gddo#455] opened 2016-11-06 23:37 UTC
The "godoc" tool is GOARCH/GOOS aware. Check this:
```
GOARCH=amd64   godoc github.com/dolmen-go/endian
GOARCH=mips64  godoc github.com/dolmen-go/endian
GOARCH=unknown godoc github.com/dolmen-go/endian
```
It would be helpful if godoc could provide the same feature using GOARCH/GOOS query parameters:
* https://godoc.org/github.com/dolmen-go/endian?GOARCH=amd64
* https://godoc.org/github.com/dolmen-go/endian?GOARCH=mips64
* https://godoc.org/github.com/dolmen-go/endian?GOARCH=unknown

**Comment by shurcooL** [comment] 2016-11-06 23:41
Thanks for opening this issue. I'll close it because it's a duplicate of #188.

**Closed by shurcooL** 2016-11-06 23:41 UTC
Labels: duplicate
