### ISSUE TITLE
Internal server error for golang.org/x/mobile/cmd/gomobile

### ISSUE THREAD

**Issue by rakyll** [golang/gddo#292] opened 2015-07-14 03:08 UTC
```
curl -v http://godoc.org/golang.org/x/mobile/cmd/gomobile
* Hostname was NOT found in DNS cache
*   Trying 108.170.219.33...
* Connected to godoc.org (108.170.219.33) port 80 (#0)
> GET /golang.org/x/mobile/cmd/gomobile HTTP/1.1
> User-Agent: curl/7.37.1
> Host: godoc.org
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
* Server nginx/1.2.1 is not blacklisted
< Server: nginx/1.2.1
< Date: Tue, 14 Jul 2015 03:07:45 GMT
< Content-Type: text/plain; charset=utf-8
< Content-Length: 22
< Connection: keep-alive
<
* Connection #0 to host godoc.org left intact
Internal server error.%
```

**Comment by adg** [comment] 2015-07-14 03:39
dupe of #286

**Closed by adg** 2015-07-14 03:39 UTC
