### ISSUE TITLE
Separate internal packages from the package listing

### ISSUE THREAD

**Issue by broady** [golang/gddo#408] opened 2016-05-12 17:46 UTC
For example, on this page:
https://godoc.org/google.golang.org/cloud

Any package path with "internal" in it should be listed in a separate section.

**Comment by shurcooL** [comment] 2016-05-12 18:03
Related to #402.

**Comment by rakyll** [comment] 2016-08-03 01:56
We can mark this as a duplicate of #402. Let's keep the convo at a single thread.

**Closed** 2016-08-03 02:16 UTC
Labels: feature, help-wanted
