### ISSUE TITLE
gddo on app engine considers all requests to be robots

### ISSUE THREAD

**Issue by sbinet** [golang/gddo#393] opened 2016-04-12 07:48 UTC
it used to be possible to click at the bottom of a package page on "imported by XX packages" and you would land on _e.g._ https://godoc.org/golang.org/x/image/math/fixed?importers

and then you could click on each of the importers' path to land on the godoc page for that importer.

it doesn't seem to be possible anymore. (the paths are not clickable anymore.)

**Comment by shurcooL** [comment] 2016-04-12 07:59
I can confirm, this is a pretty significant issue. I'm not sure how it regressed. I've looked over the last 3 commits briefly, and didn't spot a change that would obviously break this (but maybe I overlooked it).

I know this was working relatively recently (at least 3-7 days ago).

**Comment by shurcooL** [comment] 2016-04-12 08:07
Tried the latest commit locally, and the issue does not occur.

I think credentials/setup are to blame. In fact, the issue is more serious than just not seeing links, it seems that godoc.org display docs for new repositories right now. E.g., here's a repo I've created a 2 days ago, showing "Not Found":

https://godoc.org/github.com/shurcooL/issuesapp

Here's one from long ago, working:

https://godoc.org/github.com/shurcooL/htmlg

**Comment by sbinet** [comment] 2016-04-12 09:20
(FYI: I can confirm it was working last week as well)

**Comment by stephenmw** [comment] 2016-04-12 12:38
I am working on new hosting for godoc.org using App Engine. Apparently something is misconfigured. I will look into it. In the mean time I rolled back the DNS change.

**Comment by stephenmw** [comment] 2016-04-12 23:12
After some debugging we figured out the problem. When we run godoc.org on app engine, every request is considered a robot. We will tweak the algorithm and then retry deploying to GAE.

**Comment by stephenmw** [comment] 2016-04-13 17:35
Reassigned to shantuo who is working on the fix.

**Closed** 2016-04-14 00:33 UTC
Labels: operations
