### ISSUE TITLE
Docs unavailable for a go-gettable package

### ISSUE THREAD

**Issue by zenazn** [golang/gddo#355] opened 2015-12-05 20:34 UTC
I've set up a vanity import at the root of a domain, which `go get` appears to be happy with:

    go get goji.io

However, GoDoc.org appears to be unable or unwilling to show documentation for that package: https://godoc.org/goji.io

Sub-packages appear to work just fine: https://godoc.org/goji.io/pat

**Comment by rjeczalik** [comment] 2015-12-05 20:55
@zenazn `curl -sSL goji.io?go-get=1` does not contain `<meta name="go-source" ...>` header.

**Comment by shurcooL** [comment] 2015-12-05 21:19
@rjeczalik is right. You need to have that meta header as documented at:

https://golang.org/cmd/go/#hdr-Remote_import_paths

The problem is in `go get` for not returning an error. I wonder why that happens...

**Comment by shurcooL** [comment] 2015-12-05 21:23
@rjeczalik, the requirement, as documented [here](https://golang.org/cmd/go/#hdr-Remote_import_paths), is to contain a `<meta name="go-import" ...>` header, not "go-source". "go-source" is optional and unrelated.

```
$ curl -sSL 'goji.io?go-get=1' | grep "go-import"
    <meta name="go-import" content="goji.io git https://github.com/goji/goji">
```

This looks like it might be a valid issue. I'm looking into it now.

**Comment by shurcooL** [comment] 2015-12-05 21:55
The problem is in `golang.org/x/tools/go/vcs` package, [`vcs.RepoRootForImportDynamic` func](http://gotools.org/golang.org/x/tools/go/vcs#vcs-go-L483-L486).

It does not allow vanity import paths without a slash.

After re-reading documentation on remote import paths at https://golang.org/cmd/go/#hdr-Remote_import_paths, I don't see any restrictions that an import path must contain a slash. Plenty of packages have import paths that do not, e.g., "fmt" and "bytes".

So as far as I can tell, it's a bug that should be reported in the Go issue tracker.

Actually, I just remembered that gddo [does not use `x/tools/go/vcs`](https://github.com/golang/gddo/issues/204). I think for gddo, this problem lies here in `github.com/golang/gddo/gosrc.IsValidRemotePath`:

http://gotools.org/github.com/golang/gddo/gosrc#path-go-L27-L32

Can someone confirm that the requirement for a remote import path to contain a slash is invalid? I don't see such requirement documented anywhere.

**Comment by rjeczalik** [comment] 2015-12-05 22:07
@shurcooL Classy digging :+1:

Sorry for misleading, I've only compared `curl -sSL goji.io?go-get=1` vs `curl -sSL goji.io/pat?go-get=1`, the latter returns both `go-import` and `go-source`.

**Comment by zenazn** [comment] 2015-12-05 22:18
@rjeczalik—thanks for pointing that out: it's a bug on my part (that I probably wouldn't have noticed until later, so thank you!), but as @shurcooL noted it shouldn't be related to this issue.

@shurcooL—I too was unable to find a documented reason why a vanity import path must contain a slash. In fact, the implementation of `go get` seems to me to be a "living specification" of sorts: any behavior it allows should probably be accepted by the remainder of the standard (or semi-standard) Go tools.

**Comment by shurcooL** [comment] 2015-12-05 22:23
@zenazn, would you be willing to report the issue for `golang.org/x/tools/go/vcs` package in the Go issue tracker for this?

https://github.com/golang/go/issues/new?title=x/tools/go/vcs:%20

I think we should do that, have it be accepted/confirmed, then making a PR for `gosrc` and CL for `x/tools/go/vcs` is trivial.

**Comment by zenazn** [comment] 2015-12-05 22:30
Sure—I filed https://github.com/golang/go/issues/13506 to track this bug.

**Comment by shurcooL** [comment] 2015-12-05 22:53
Thanks a lot! I've subscribed to that issue and I can make the PRs/CSes once we have the clarification.

**Comment by zenazn** [comment] 2015-12-28 20:46
As an update here (https://github.com/golang/go/issues/13506), fetching packages at the root of a domain is new as of Go 1.5 (https://github.com/golang/go/issues/9357; https://github.com/golang/go/commit/2f54de0df8cf362a4ffd374e2eb752b0c57115d5), and `godoc.org` and `x/tools/go/vcs` both need to be updated to reflect this new behavior.

**Comment by shurcooL** [comment] 2015-12-29 06:07
I've made PR #362 and [CL 18152](https://golang.org/cl/18152) to address the issues. They need to be reviewed and merged.

**Comment by zenazn** [comment] 2015-12-29 16:23
Awesome. Thanks so much, @shurcooL!

**Comment by shurcooL** [comment] 2015-12-29 22:05
[CL 18152](https://golang.org/cl/18152) has been merged. As a result, https://gotools.org/goji.io now works successfully.

Still waiting on PR #362 to be review, merged, and godoc.org redeployed before https://godoc.org/goji.io will work.

**Closed** 2016-01-25 07:47 UTC

**Comment by shurcooL** [comment] 2016-01-25 08:40
#362 is now merged, and godoc.org appears to be redeployed, because https://godoc.org/goji.io now works. /cc @zenazn

Thanks Andrew!

**Comment by adg** [comment] 2016-01-25 08:49
Thanks for fixing the code!

**Comment by shurcooL** [comment] 2016-01-25 08:52
No problem, I'm always happy to jump at an opportunity to make Go a little bit better! :P
