### ISSUE TITLE
Fails to display docs for package with import path containing non-ASCII letters.

### ISSUE THREAD

**Issue by mcandre** [golang/gddo#468] opened 2017-01-11 01:20 UTC
When I try to upload documentation for a package with a Cyrillic name, instead the Go docs website redirects to the parent package.

Example:

Try to send испытание ("ispitanye") to the Go docs website.

https://github.com/mcandre/toys/tree/master/go/испытание

**Comment by shurcooL** [comment] 2017-01-11 04:11
I can confirm, it displays "Not Found":

https://godoc.org/github.com/mcandre/toys/go/испытание

**Comment by shurcooL** [comment] 2017-01-11 04:15
Are you sure it's a valid import path? I'm trying to `go get` it and it fails:

```
$ go get -u github.com/mcandre/toys/go/испытание
package github.com/mcandre/toys/go/испытание: invalid github.com/ import path "github.com/mcandre/toys/go/испытание"
```

Using `go version go1.8rc1 darwin/amd64`.

**Comment by mcandre** [comment] 2017-01-11 23:16
Good point, might need to `git clone` instead of `go get`, since `go get` appears to react poorly to Unicode paths.

**Comment by shurcooL** [comment] 2017-01-11 23:18
Then it's not an issue in godoc.org. Its responsibility is to display documentation for import paths that `go get` can successfully retrieve.

I think we should open an issue in the Go project and fix `go get` not working first. Then followup in godoc.org.

**Comment by jrep2** [comment] 2017-01-12 00:25
The problem is [on this line](https://github.com/golang/gddo/blob/806603679dee755c926f72ac76673ee4594dcd32/gosrc/github.go#L21).

**Comment by shurcooL** [comment] 2017-01-18 01:45
> Did you already report it there?

It has been reported in golang/go#18660.

**Comment by shurcooL** [comment] 2017-01-18 03:02
Since the "github.com/" import path issue is blocked on golang/go#18660 being resolved, let's repurpose this issue for something related that is valid and can be resolved in gddo now.

The following is a valid vanity import path:

```
dmitri.shuralyov.com/temp/go-get-issue-unicode/испытание
```

You can `go get` it and everything successfully. However, gddo fails to display documentation for it, saying "Not Found":

https://godoc.org/dmitri.shuralyov.com/temp/go-get-issue-unicode/испытание

The reason is because [`gosrc.IsValidRemotePath`](https://godoc.org/github.com/golang/gddo/gosrc#IsValidRemotePath) has a problem. It should return true, since `go get` works on that import path, but it actually returns false:

```
$ goexec 'gosrc.IsValidRemotePath("dmitri.shuralyov.com/temp/go-get-issue-unicode/испытание")'
(bool)(false)
```

The cause for that is here:

https://github.com/golang/gddo/blob/806603679dee755c926f72ac76673ee4594dcd32/gosrc/path.go#L18

That regexp does not permit non-ASCII letters.

**Comment by shurcooL** [comment] 2017-04-25 19:53
I've created [CL 41750](https://go-review.googlesource.com/c/41750/) which fixes this bug.

**Closed** 2017-04-25 20:38 UTC
Labels: bug
