### ISSUE TITLE
support default branches other than "master"

### ISSUE THREAD

**Issue by kr** [golang/gddo#405] opened 2016-05-05 16:59 UTC
This is pretty much the same issue as https://golang.org/issue/9032.

Example: docs for github.com/kr/text are currently unavailable because the default branch on that repo is "main". See https://godoc.org/github.com/kr/text.

**Comment by jackcohen** [comment] 2016-05-06 00:57
Duplicate of #398

**Comment by kr** [comment] 2016-05-07 21:43
I had thought this bug report would be pretty uncontroversial, but in https://github.com/golang/go/issues/15580#issuecomment-217668913, @minux said:

> [Using a default branch other than "master"] also breaks pre Go 1.6 go get, so I'm not sure if we should encourage that.

It seems like quite a stretch to say that gddo should halt fixing bugs just to force everyone to continue using workarounds for old, buggy releases of Go.

(It may be true that developers of packages (such as github.com/kr/text) have a social obligation to provide workarounds while buggy tools are still in common use. But that's a different thing entirely.)

**Comment by shurcooL** [comment] 2016-05-07 21:52
> It seems like quite a stretch to say that gddo should halt fixing bugs just to force everyone to continue using workarounds for old, buggy releases of Go.

I agree this bug should be fixed. gddo should follow behavior of Go. It's just a matter of someone making a CL and it being reviewed.

**Comment by adg** [comment] 2016-05-09 17:48
Also agree this should be fixed.

**Closed** 2016-06-30 21:47 UTC
