### ISSUE TITLE
func not visible in doc.

### ISSUE THREAD

**Issue by splace** [golang/gddo#379] opened 2016-02-23 22:32 UTC
see;  https://godoc.org/github.com/splace/sounds/examples/DTMF

it does have in-page links to the, non-existent, func documentation.

**Comment by shurcooL** [comment] 2016-02-23 23:14
I can confirm, that appears to be a bug in gddo.

There's clearly a `func DuelTone` in the file:

https://github.com/splace/sounds/blob/99e1d9ebb1522964d5bf16d793e35475fa0af99c/examples/DTMF/tones.go#L9

The .go file is not `gofmt`ed and contains a dot import, but even if discouraged, those are valid things to do, so they should work.

**Comment by splace** [comment] 2016-02-24 16:50
here's a guess at whats happening;

the documenter must know that the return type is an interface, (to know this it has to have checked the external package, and know its an externally defined interface!), and by having an interface type return value, the func could be listed under the type as a constructor, IF its in the same package. which is when it seems to make the mistake of relying on the absence of a package qualifier to check this, when actually the fact that its an external interface means it already knows it has to print it.

**Comment by lucidlime** [comment] 2016-02-26 16:28
Fixed by https://github.com/golang/go/commit/ee566d53adb075c63dc036adb96ba643478a1e00

**Comment by shurcooL** [comment] 2016-02-27 00:20
Great. Recompiling and deploying new version of gddo should fix that repo, and then this issue can be closed.

**Comment by adg** [comment] 2016-02-29 02:17
I've re-deployed godoc.org but the issue doesn't seem to be solved.

**Comment by shurcooL** [comment] 2016-02-29 02:21
Hmm.

The fix is in `go/doc` package of standard library, which means gddo won't see it until Go 1.7 comes out, right?

**Comment by shurcooL** [comment] 2016-02-29 02:23
One idea could be to vendor the fixed `go/doc` package in `github.com/golang/gddo/vendor/go/doc`.

Of course, before doing that, should verify it actually fixes the problem, because it may simply be elsewhere in gddo's code.

**Comment by adg** [comment] 2016-02-29 02:23
I'm happy deploying godoc.org from go tip.

**Comment by shurcooL** [comment] 2016-02-29 02:33
This is unexpected, but I can't reproduce the issue locally with just the latest `master` version of `gddo`:

```
$ go version
go version go1.6 darwin/amd64
```

![image](https://cloud.githubusercontent.com/assets/1924134/13384357/b5baac56-de49-11e5-9828-b4783ced71a3.png)

**Comment by shurcooL** [comment] 2016-02-29 02:38
Okay, it makes sense now. That commit https://github.com/golang/go/commit/ee566d53adb075c63dc036adb96ba643478a1e00 is actually a part of Go 1.6, that's why I'm not seeing an issue locally.

What version of Go is gddo deployed with now? It seems just Go 1.6 would be enough to fix it (assuming it's something older now).

**Comment by adg** [comment] 2016-02-29 04:07
Re-deployed from Go 1.6 and the issue is now resolved.

**Closed by adg** 2016-02-29 04:07 UTC

**Comment by shurcooL** [comment] 2016-02-29 04:25
That may have caused a regression?

Refreshing any Go package currently gives a "Error refreshing package: Error getting package files from api.github.com." error.

**Comment by adg** [comment] 2016-02-29 04:43
Yeah I'm currently battling with a strange issue where gddo-server doesn't
believe it's on gce an so isn't fetching credentials from the metadata
server :-/

**Comment by adg** [comment] 2016-02-29 04:56
Should be fixed now.

**Comment by shurcooL** [comment] 2016-02-29 05:29
Confirmed fixed. https://godoc.org/github.com/nodirt/tmp/godoc-bug is also good now (after successfully refreshing).
