### ISSUE TITLE
BUG comments in command packages don't show up

### ISSUE THREAD

**Issue by natefinch** [golang/gddo#161] opened 2014-04-02 11:45 UTC
// BUG(foo) style comments show up in the bugs section of library packages, but not in command packages.  Local godoc does show these bugs. This seems like a pretty serious problem, since it can mean missing some important information about the application.

**Comment by LaPingvino** [comment] 2015-02-08 20:27
# For future reference and for my own bughunting:
Found example import path to test with at: github.com/bmatsuo/grandall.exp/cmd/grandall
Example of working library bug listing: godoc.org/sync/atomic
Example of working library bug listing outside the standard library: github.com/yosabra/prometheus/coding

**Comment by LaPingvino** [comment] 2015-02-08 21:42
For some reason bugs are put in .pdoc.Notes for packages, but not for commands. Didn't manage to find out where this distinction happens though. Would be very helpful to know where the bugs are filled in the notes field for packages...

**Comment by garyburd** [comment] 2015-02-08 23:03
The [command template](https://github.com/golang/gddo/blob/bb20f8c58cabb359ba8de621fdd304c020d8c63c/gddo-server/assets/templates/cmd.html) does not show bug comments. One possible fix is to move the [bug comment section of the package template](https://github.com/golang/gddo/blob/bb20f8c58cabb359ba8de621fdd304c020d8c63c/gddo-server/assets/templates/pkg.html#L147-L149) to [the footer shared by packages and commands](https://github.com/golang/gddo/blob/master/gddo-server/assets/templates/common.html#L58).

**Comment by LaPingvino** [comment] 2015-02-08 23:30
I did exactly that locally, but the problem is that the data structure used to fill this in seems to contain the bug information in the case of a package, but not for a command (testing with the example paths mentioned earlier). See my version at https://github.com/LaPingvino/gddo/compare/golang:master...bug-comments to test this. Locally between {{with .pdoc}} and {{with .Notes}}, and thereafter between {{with .Notes}} and {{with .BUG}} I used a {{.}} to inspect the contents when testing.

**Comment by garyburd** [comment] 2015-02-09 00:39
The command github.com/bmatsuo/grandall.exp/cmd/grandall does not have bug comments. Try testing with golang.org/x/tools/cmd/godex.

**Comment by LaPingvino** [comment] 2015-02-09 00:44
Thanks for the catch! Just verified that the code in the patch does indeed fix it then! I will create a pull request.

**Comment by garyburd** [comment] 2015-02-09 23:25
Fixed by ae40bf0a3fe00fc6f9c948bf678239abca7db30b.

**Closed** 2015-02-09 23:47 UTC
Labels: help-wanted
