### ISSUE TITLE
talksapp: talks.godoc.org slide progression is out of phase with slide width

### ISSUE THREAD

**Issue by kortschak** [golang/gddo#449] opened 2016-10-12 23:24 UTC
### What did you do?

Go to e.g. http://talks.godoc.org/github.com/SatishTalim/slides/whygo.slide (browsing with FF48.0) and progress through a number of slides.
### What did you expect to see?

Slide progression where slide n+1 is aligned with the previous position of slide n.
### What did you see instead?

Slides progressively move to the left (animation shifts more than one slide width to the left each step).

**Comment by shurcooL** [comment] 2016-10-16 23:32
I can't seem to reproduce in either Chrome 54.0.2840.59 (current stable version), nor Firefox Developer Edition 51.0a2 (2016-10-15).

Is it an issue that's affecting Firefox 48.0 only? Is that the current stable version of Firefox, or is it out of date? If so, can you check if the current version has the same issue?

**Comment by kortschak** [comment] 2016-10-16 23:48
Just upgraded to 49.0. Problem remains.

**Comment by shurcooL** [comment] 2016-10-17 03:32
I cannot reproduce this.

I tried a fresh VM of Ubuntu 16.10 just now, which comes with Firefox 49.0. I did not spot any issues with slides moving to the left. Here's a quick screencapture:

http://instantshare.virtivia.com:27080/15n83krlqf2n3.mov

Can you provide more information to try to help reproduce this? What OS are you using? Have you tried turning off any extensions you might have, clearing browser cache, using incognito window. Tried on another computer?

**Comment by kortschak** [comment] 2016-10-17 03:51
I am using ubuntu 12.04 (hopefully for not much longer - an upgrade window is coming soon).

Clearing cache, turning off all extensions or icognito mode do not fix this.

The reproduction is really as simple as described above. Here is how it looks after having progressed right by 9 slides.

![out-of-register](https://cloud.githubusercontent.com/assets/275221/19424887/c4373e70-9474-11e6-861a-836fc1d0f620.png)

I will try this on another machine (16.04) when I can later today.

**Comment by kortschak** [comment] 2016-10-17 08:22
Not reproducible on 16.04.

**Closed** 2016-11-07 01:46 UTC
Labels: talksapp
